@REQ-ZS-227 @BEH-ZS-262 @mvp
Feature: Version-managed templates

  Scenario: Activating a version validated against a real file
    Given a grade file actually generated by Massar, provided by a pilot school for the middle-school cycle, semester 1, 2026-2027 year
    When ZSchool support creates the version "grades-middle-S1-2026-2027" and validates it against that file
    Then the version is activated for every school with no rollout
    And the export wizard offers it with a column preview and its activation date

  Scenario: Retired version stays viewable
    Given a template version retired after an observed structure change
    When leadership views the export history produced with that version
    Then earlier files stay exactly reproducible and the version is marked "retired"
    And no new export can use it
