packages:
  - "apps/*"
  - "packages/*"

catalog:
  effect: 4.0.0-rc.115
  "@effect/platform-node": 4.0.0-rc.115
  "@effect/platform-node-shared": 4.0.0-rc.115
  "@effect/sql-pg": 4.0.0-rc.115
  "@effect/vitest": 4.0.0-rc.115
  "@effect-cucumber/gherkin": 0.10.0
  "@effect-cucumber/vitest": 0.10.0
  "@qadi/core": 0.6.2
  "@qadi/http": 0.6.2
  "@qadi/testing": 0.6.2
